export * from './MainPage'
export * from './LoginPage'
export * from './ProfilePage'
export * from './NotfoundPage'
export * from './CreateAccountPage'
export * from './ProfileInfoPage'
export * from './OrdersHistoryPage'
